name: Test

on:
  push:
    branches:
      - main
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repo
      uses: actions/checkout@v3

    - name: Install Dependencies
      run: sudo apt update && sudo apt install -y build-essential

    - name: Run make
      run: make

    - name: run make install
      run: sudo make install

    
      

    
      

    
    
